on:
  push:
    branches:
      - master
name: 🚀 Deploy to Master
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: ♻ Use Node.js 12
      uses: actions/setup-node@v2-beta
      with:
        node-version: '12'

    - name: 🔨 Build VueJS Project
      run: |
        npm install
        npm run build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: dist/
        server-dir: /projects.shinodalabs.com.br/luxury-hotels/
